### PR TITLE
Fix ECOS_updateData()

### LINKED ISSUE #183: Redundant unset_equilibration in ECOS_updateData()
It looks like this call to `unset_eqilibration()` is redundant since the matrices and vectors that get restored by it are overwritten right after. This would not be an issue by itself, but is very inconvenient since it forces the user to alternate between two locations in memory for the `A`, `G`, `c`, `h`, `b` data between calls to `ECOS_updateData()` and `ECOS_solve()`.

https://github.com/embotech/ecos/blob/d0a0551827a3f7b01dee261604ef02c5706d8c15/src/ecos.c#L1655

### PR DESCRIPTION
**Pull request by EmbersArc**
Fix #183 and allow for updates when no equality and/or inequality constraints are present in the problem.

---
This change is [Reviewable](https://reviewable.io/reviews/embotech/ecos/185)

### CODE REVIEW

File: src/ecos.c [hunk 1]
```diff
@@ -1652,25 +1652,42 @@ void ECOS_updateData(pwork *w, pfloat *Gpr, pfloat *Apr,
...
+        w->A->pr = Apr;
+        w->b = b;
+    }
     w->c = c;
-    w->h = h;
-    w->b = b;
 
 #if defined EQUILIBRATE && EQUILIBRATE > 0
     set_equilibration(w);
 #endif
```
Comment (smerkli) [inline src/ecos.c]: @EmbersArc I've been thinking about this and it seems that this change makes it so that `unset_equilibration` happens  only if the conditions are met, but `set_equilibration` happens unconditionally. This could mean the data gets equilibrated multiple times in a row without a corresponding un-equilibration. 

I'm not that familiar with the equilibration process - have you looked into this more? If what I'm describing is not an issue, maybe adding a comment saying so to the `set_equilibration` call here would help avoid future confusion.

Comment (EmbersArc) [reply src/ecos.c]: Thanks for the review. In my view, the equilibration can be done unconditionally. The new data is always expected to be unequilibrated. The first check only happens to make sure that the old data gets unequilibrated if it did not get overwritten by the new data. Existing code using this function might rely on this step. I added some comments to make this clearer.

**Review by smerkli — APPROVED** [review]
Thanks for the functionality and adding comments to make it clear to readers.
